spring.application.name=token-market
app.data.path=${user.home}/.futbol-token-market/tokens.json
app.users.path=${user.home}/.futbol-token-market/users.json
app.players.path=${user.home}/.futbol-token-market/players.json
app.teams.path=bin/main/data/teams.json
jwt.secret=cambiar-esto-por-un-secreto-seguro-de-al-menos-256-bits-en-produccion
jwt.expiration-ms=86400000
football.data.api.token=82d59be660724438a0020cfd739c1413
